<?php

namespace MusicStation\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoutRepository extends EntityRepository
{
}
