# MusicStationSiteBundle controllers
music_station_site:
    resource: "@MusicStationSiteBundle/Controller/"
    type:     annotation
    prefix:   /

# MusicStationUserBundle controllers
music_station_user:
    resource: "@MusicStationUserBundle/Controller/"
    type:     annotation
    prefix:   /