MusicStation\UserBundle\Entity\Event:
    properties:
        location:
            - NotBlank: ~
        startDate:
            - DateTime: ~

MusicStation\UserBundle\Entity\Shout:
    properties:
        message:
            - NotBlank: ~